name: Deploy ms-usuario to Google Cloud Run

on:
  push:
    branches:
      - main
      - develop

env:
  PROJECT_ID: project-f27c5714-ec0c-4985-a97
  REGION: us-central1
  ARTIFACT_REGISTRY: us-central1-docker.pkg.dev
  SERVICE_NAME: ms-usuario

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ARTIFACT_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Docker image
        run: |
          IMAGE_PATH="${{ env.ARTIFACT_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          
          echo "Building image: $IMAGE_PATH"
          docker build -t $IMAGE_PATH .
          
          echo "Pushing image..."
          docker push $IMAGE_PATH
          
          echo "IMAGE_NAME=$IMAGE_PATH" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE_NAME }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8081 \
            --timeout 300 \
            --add-cloudsql-instances="${{ secrets.CLOUD_SQL_INSTANCE }}" \
            --memory 2Gi \
            --no-cpu-throttling \
            --set-env-vars="SPRING_PROFILES_ACTIVE=cloud,\
                            JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m,\
                            DB_FLYWAY_URL=jdbc:postgresql:///usuario_db?cloudSqlInstance=${{ secrets.CLOUD_SQL_INSTANCE }}&socketFactory=com.google.cloud.sql.postgres.SocketFactory,\
                            DB_URL=jdbc:postgresql://localhost/usuario_db?cloudSqlInstance=${{ secrets.CLOUD_SQL_INSTANCE }}&socketFactory=com.google.cloud.sql.postgres.SocketFactory,\
                            DB_USERNAME=postgres,\
                            DB_PASSWORD=${{ secrets.DB_PASSWORD }},\
                            REDIS_HOST=10.181.93.59,\
                            REDIS_PORT=6379,\
                            LOGSTASH_HOST=logstash-service-791247002252.us-central1.run.app,\
                            LOGSTASH_PORT=443,\
                            SERVER_FORWARD_HEADERS_STRATEGY=framework,\
                            MANAGEMENT_TRACING_ENABLED=false,\
                            SPRING_FLYWAY_BASELINE_ON_MIGRATE=true,\
                            SPRING_ZIPKIN_ENABLED=false"
